### PR TITLE
Addin Lab05branch to Paz

### PR DESCRIPTION
**Pull request by foxbat07**
making the pull request for lab 05

### CODE REVIEW

**Comment by foxbat07** [comment]
hope this works!

**Comment by PazZaitGivon** [comment]
please don't edit files that say not to edit them such as the build.xml; can you change it back to not include your name?

**Comment by foxbat07** [comment]
sure!

On Mar 8, 2015, at 12:18 PM, Paz Zait-Givon notifications@github.com wrote:

please don't edit files that say not to edit them such as the build.xml; can you change it back to not include your name?

**Comment by PazZaitGivon** [comment]
let me know when you do that so I can accept the pull request!

**Comment by foxbat07** [comment]
Did the initial build.xml have the author as a ? Or there was not second author?

**Comment by PazZaitGivon** [comment]
the initial build only had phill conrad as the author

**Comment by foxbat07** [comment]
just made a request

On Mar 8, 2015, at 2:09 PM, Paz Zait-Givon notifications@github.com wrote:

the initial build only had phill conrad as the author

**Comment by PazZaitGivon** [comment]
the second author is still there

**Comment by foxbat07** [comment]
i was on the wrong branch.

oops

On Mar 8, 2015, at 2:20 PM, Paz Zait-Givon notifications@github.com wrote:

the second author is still there

**Comment by foxbat07** [comment]
just sent another request

On Mar 8, 2015, at 2:20 PM, Paz Zait-Givon notifications@github.com wrote:

the second author is still there

**Comment by PazZaitGivon** [comment]
Great thanks!

**Comment by foxbat07** [comment]
Thanks Paz!

**Comment by foxbat07** [comment]
Is this what you need?

https://github.com/UCSB-CS56-W15/cs56_w15_feedback_mohithingorani/blob/master/lab08.md

sorry about the late submission :)

Mohit

On Mar 8, 2015, at 3:13 PM, Mohit Hingorani <hingoranimohit@gmail.com<mailto:hingoranimohit@gmail.com>> wrote:

Thanks Paz!

Sent from my iPhone

On Mar 8, 2015, at 3:12 PM, Paz Zait-Givon <notifications@github.com<mailto:notifications@github.com>> wrote:

Merged #17https://github.com/PazZaitGivon/W15-lab04/pull/17.

—
Reply to this email directly or view it on GitHubhttps://github.com/PazZaitGivon/W15-lab04/pull/17#event-248227115.

Mohit Hingorani
Graduate Student
Media Arts & Technology Graduate Program
Technology Management Program
University of California,Santa Barbara
Santa Barbara, CA 93106-9650
mohit@mat.ucsb.edumailto:mohit@mat.ucsb.edu
www.mohithingorani.comhttp://www.mohithingorani.com

**Pull request merged**
